apiVersion: apps/v1
kind: Deployment
metadata:
  name: dormproject-backend
spec:
  replicas: 1 # or the desired number of replicas
  selector:
    matchLabels:
      app: dormproject-backend
  template:
    metadata:
      labels:
        app: dormproject-backend
    spec:
      containers:
        - name: dormproject
          image: telgou/dormproject:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://db-mysql:3306/backend?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dormproject-backend
spec:
  selector:
    app: dormproject-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-mysql
  template:
    metadata:
      labels:
        app: db-mysql
    spec:
      containers:
        - name: db-mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: backend
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: db-mysql-service
spec:
  selector:
    app: db-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-mysql
  template:
    metadata:
      labels:
        app: db-mysql
    spec:
      containers:
        - name: db-mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: backend
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/mysql
          volumes:
            - name: db-volume
              emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1 # or the desired number of replicas
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: front
          image: front
          ports:
            - containerPort: 4200
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
  type: ClusterIP
