apiVersion: v1
kind: Service
metadata:
  name: dbmysql-service
spec:
  selector:
    app: dbmysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbmysql
  template:
    metadata:
      labels:
        app: dbmysql
    spec:
      containers:
        - name: dbmysql
          image: mysql:5.6
          ports:
            - containerPort: 3306
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: db-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: dormproject-backend
spec:
  selector:
    app: dormproject-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dormproject-backend
spec:
  replicas: 1 # or the desired number of replicas
  selector:
    matchLabels:
      app: dormproject-backend
  template:
    metadata:
      labels:
        app: dormproject-backend
    spec:
      containers:
        - name: dormproject
          image: telgou/dormproject:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://db-mysql:3306/backend?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
  restartPolicy: Always
---