version: "3.9"
services:

  backend:
    container_name: dormproject
    image: "dormproject"
    #build: .\backend
    hostname: dormproject
    ports:
      - "8081:80"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/backend?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: on-failure
    networks:
      - devops
    depends_on:
      - "db-mysql"
      - "nginx"

  angular-app:
    container_name: front
    build: 
      context: ../front
      dockerfile: dockerfile
    image: front
    ports:
      - "4200:80"
    restart: always
    networks:
      - devops 
    depends_on:
      - "db-mysql"
      - "nginx"  

  nginx:
    image: nginx:latest
    ports:
      - 80:80 

  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=backend
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - devops

networks:
  devops:
    driver: bridge
