name: Jenkins Pipeline Trigger

on:
  push:
    branches:
      - main # Change this to match your branch name

jobs:
  trigger_jenkins_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST -u admin:11db9cf6eb01605e3e15e7944cf89f8ac3 \
          http://192.168.253.129:8080/job/spring%20pipeline/build?token=automatic
